# Generated by Django 4.2.5 on 2024-01-20 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('Task_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=300)),
                ('DueDate', models.CharField(max_length=50)),
                ('Status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'In_progress')])),
                ('Priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
                ('Notes', models.CharField(default='', max_length=100)),
                ('Date_Created', models.DateField(auto_now_add=True)),
                ('Date_Completed', models.CharField(default='N/A', max_length=50)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_Django.record')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('Opportunity_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Deal_Name', models.CharField(max_length=100)),
                ('Stage', models.IntegerField(choices=[(0, 'Prospecting'), (1, 'Negotiation'), (2, 'Closed-Won'), (3, 'Closed-Lost')])),
                ('Expected_close_date', models.CharField(max_length=40)),
                ('Notes', models.CharField(default='', max_length=30)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_Django.record')),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('Interaction_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
                ('Type', models.IntegerField(choices=[(0, 'Call'), (1, 'Email'), (2, 'meeting')])),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_Django.record')),
            ],
        ),
    ]
