# Generated by Django 4.2.5 on 2024-01-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Django', '0002_alter_record_phone_tasks_opportunities_interactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=110)),
                ('Date_ordered', models.DateTimeField(auto_now_add=True)),
                ('Status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Delivered'), (2, 'Cancelled')])),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_Django.record')),
            ],
        ),
    ]
