# Generated by Django 4.2.5 on 2024-01-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Django', '0004_alter_interactions_interaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsdkf', models.CharField(max_length=100)),
            ],
        ),
    ]
