# Generated by Django 4.2.5 on 2024-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Django', '0005_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hi',
        ),
    ]
