# Generated by Django 4.2.5 on 2024-01-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Django', '0006_delete_hi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date_ordered',
            field=models.DateTimeField(),
        ),
    ]
