# Generated by Django 4.2.5 on 2024-01-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_Django', '0007_alter_orders_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date_ordered',
            field=models.DateField(),
        ),
    ]
